### ISSUE TITLE
apps shared from web are not showing on android in fastboard. 

### ISSUE THREAD

**Issue by anshArtium** [netless-io/fastboard-android#1]
Only the apps window controls are visible to the android user but not the content,  when maximized. we can control full screen/ minimize the window from android side, but the content is not visible. The drawing controls are working fine, only need help with the apps shared like YouTube videos. @aderan @AderanFeng

**Comment by aderan** [comment]
@anshArtium 
Thank you for the question. Fastboard comes with some built-in apps like Slide, MediaPlayer, and DocsViewer. To add other kinds of apps, you need to register them after joining the room.

For playing YouTube videos, you'll need to register the Plyr app. Please refer to the [**registerApps**](https://github.com/netless-io/fastboard-android/blob/ec6a54179d0c5f8bda7faa4c327f71f055537bc3/app/src/main/java/io/agora/board/fast/sample/cases/RoomActivity.java#L134C15-L134C15) section for more details on how to register additional apps.

Let me know if you need any clarification or have additional questions! I'd be happy to explain further.
