### ISSUE TITLE
How to implement custom apps

### ISSUE THREAD

**Issue by anshArtium** [netless-io/fastboard-android#2]
I want to show browser , youtube player (i am using browser and youtube features on web side using register App) and screen share for android fastboard to web fastboard, which will close when fastboard closes. I am trying to use the room.addApp method where i am passing Promise<String> and WindowAppParam(String kind, Options options, Attributes attributes) but am not able to send any links with the attributes. can you please suggest how to achieve this?

**Comment by aderan** [comment]
@anshArtium
Thank you for the question.
Our whiteboard is based on WebView and native objects are serialized and passed to WebView. For customized plugins, you need to inherit the Options and Attributes classes provided by the sdk and add the extensional attribute variables.
Specifically, you can refer to the code [addYoutubeApp](https://github.com/netless-io/fastboard-android/blob/769d62fd2fcb6b0f5753bc301a8bc0530b7eec02/app/src/main/java/io/agora/board/fast/sample/cases/helper/RoomOperationsKT.kt#L67)

**Comment by anshArtium** [comment]
Thank you for the reply, I am able to add the apps on android side. One issue is arising when i play the app on one side (web or android) and it continues to play on other side if i close the fastboard window without closing that particular app. For example: If i play a youtube video on web side to android, and close the fastboard the window without closing the youtube app (or pausing the video), the video keeps playing on the android side. Is there a method for removing/closing the app when fastboard is closed?

**Comment by aderan** [comment]
> Thank you for the reply, I am able to add the apps on android side. One issue is arising when i play the app on one side (web or android) and it continues to play on other side if i close the fastboard window without closing that particular app. For example: If i play a youtube video on web side to android, and close the fastboard the window without closing the youtube app (or pausing the video), the video keeps playing on the android side. Is there a method for removing/closing the app when fastboard is closed?

In general, the exit of a window on one side should not affect the other side. The Whiteboard SDK doesn't care if the other end exits, It is more upper level business definition. 
If you want to end the board room. exit Activity and call FastRoom.destroy().
If you just want to close the app.The new version of whiteboard-android 2.16.71 added some new App management methods. Room.queryAllApps(), Room.closeApp() might be useful for your needs.
